name: dbeaver/cloudbeaver

on:
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build DBeaver/CloudBeaver image
        run: |
          docker build --progress=plain \
          --tag ghcr.io/${{ github.repository_owner }}/dbeaver/cloudbeaver:24.2.3 \
          --file dbeaver/cloudbeaver/dockerfile \
          dbeaver/cloudbeaver      

      - name: Push the image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository_owner }}/dbeaver/cloudbeaver:24.2.3